name: Release

on:
  push:
    branches:
      - principal
      - action-publish

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: teste123
      TESTE: ${{ vars.TESTE_TOKEN_VALUE }}

    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '14'
    
    # - name: Inicializa NPM
    #   run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    # - name: Debug .npmrc
    #   run: cat ~/.npmrc

    - name: Debug NPM_AUTH_TOKEN
      run: echo $NPM_AUTH_TOKEN aaa $TESTE

    # - name: Install Dependencies
    #   run: npm install --no-save

    # - name: Release Package
    #   run: npx release-it --ci --npm.authToken=${{ secrets.NPM_AUTH_TOKEN }}
