name: Release

on:
  push:
    branches:
      - action-publish

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configurar usuário Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Instalar dependências
        run: npm install

      - name: Executar release-it
        run: npm run release
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}